services:
  registry:
    image: registry:2
    restart: always
    # ports:
    #   - 5000:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
      - REGISTRY_PROXY_USERNAME=${REGISTRY_PROXY_USERNAME}
      - REGISTRY_PROXY_PASSWORD=${REGISTRY_PROXY_PASSWORD} # Docker Hub Personal Access Token
      # - REGISTRY_AUTH=htpasswd
      # - REGISTRY_AUTH_HTPASSWD_REALM=basic-realm
      # - REGISTRY_AUTH_HTPASSWD_PATH=/run/secrets/registry_htpasswd
    volumes:
      - registry_data:/var/lib/registry
    # secrets:
    #   - registry_htpasswd  # /run/secrets/registry_htpasswd
  
  traefik:
    image: traefik:v3.2.1
    restart: always
    ports:
      - 443:443
      - 80:80
    environment:
      - REGISTRY_DOMAIN=${REGISTRY_DOMAIN}
      # Cloudflare DNS Challenge
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config/registry.yml:/etc/traefik/config/registry.yml:ro
      - ./traefik/acme:/etc/traefik/acme

secrets:
  registry_htpasswd:
    file: ./htpasswd

volumes:
  registry_data: